<template>
  <v-app id="inspire">
    <v-navigation-drawer
      v-model="drawer"
      fixed
      mobile-break-point="970"
      app
    >
      <v-card>
        <v-toolbar
          color="deep-purple"
          dark
        >

          <v-toolbar-title>{{ projectName }}</v-toolbar-title>

          <v-spacer />

        </v-toolbar>
        <v-list dense>
          <template v-for="module in modules">
            <v-list-tile
              :key="module.module_name"
              ripple
              @click="goToDocument(module)"
            >
              <v-list-tile-content>
                <v-list-tile-title
                  :class="isMatchModule(module.module_name) ? 'primary--text' : ''"
                  active-class="highlighted"
                >
                  <span>{{ module.module_name }}</span>
                </v-list-tile-title>
              </v-list-tile-content>
            </v-list-tile>
          </template>
        </v-list>
      </v-card>
    </v-navigation-drawer>
    <v-toolbar
      color="deep-purple"
      dark
      fixed
      app
    >
      <v-toolbar-side-icon @click.stop="drawer = !drawer" />
      <v-text-field
        append-icon="mic"
        clearable
        class="mx-3"
        flat
        label="Search"
        prepend-inner-icon="search"
        solo-inverted
        @keyup="changeSearchText"
      />
    </v-toolbar>
    <v-content>
      <v-container
        fluid
        fill-height
      >
        <v-slide-y-transition>
          <nuxt />
        </v-slide-y-transition>
      </v-container>
    </v-content>
    <v-footer
      height="auto"
      color="deep-purple lighten-1"
      app
    >
      <v-layout
        justify-center
        row
        wrap
      >
        <v-flex
          id="bottom"
          deep-purple
          py-2
          text-xs-center
          white--text
          xs12
        >
          generated by
          <strong>
            <a
              class="white--text"
              target="_brank"
              href="https://github.com/shufo/ex_doc_refined"
            >ExDocRefined</a>
          </strong>
        </v-flex>
      </v-layout>
    </v-footer>
  </v-app>
</template>

<script>
import { mapGetters, mapState } from 'vuex'

export default {
  middleware: ['moduledoc'],
  props: {},
  data: () => ({
    drawer: null
  }),
  head() {
    return {
      title: this.projectName
    }
  },
  computed: {
    ...mapGetters(['modules']),
    ...mapState(['projectName'])
  },
  methods: {
    changeSearchText(e) {
      this.searchInput = e.target.value
      this.$store.dispatch('changeSearchText', this.searchInput)
    },
    goToDocument(module) {
      this.$router.push(module.module_name)
      return
    },
    isMatchModule(module_name) {
      return $nuxt.$route.path === '/' + module_name
    }
  }
}
</script>
<style lang="scss">
.chart-v-list-tile {
  .v-list__tile {
    height: 300px !important;
  }
  .v-list__tile__content {
    height: 300px;
  }
}
</style>
